Feature/collecting disks
Big3ppvv/LearningJS pull request #9
Opened 2023-09-19 18:33 UTC by Big3ppvv

### Collecting Disks
**Make a new exercise of collecting objects like disks**

2023-09-19 18:33 UTC, Big3ppvv reviewed
I added a new exercise

2023-09-20 15:03 UTC, Arsentau requested changes
Why did you delete the previous exercices?

2023-09-21 14:06 UTC, Arsentau requested changes

2023-09-21 14:06 UTC, Arsentau commented on ej4-collectingDisks/exercise4.js
> +    if(valor === ""){
you are mixing Spanish and English, please fix it

2023-09-21 14:06 UTC, Arsentau commented on ej4-collectingDisks/exercise4.js
> +    }else if(propiedad === "canciones" && discos[id][propiedad] === undefined) {
this else if concatenation is making it hard to read, is there another way to implement this?

2023-09-21 14:06 UTC, Arsentau commented on ej4-collectingDisks/exercise4.js
> +var coleccionDeDiscos = {
`var` is forbbiden

2023-09-21 14:06 UTC, Arsentau commented on ej4-collectingDisks/exercise4.js
> +var propiedad = "canciones";
please not make usage of `var` to declare a variable

2023-09-21 18:09 UTC, Big3ppvv commented on README.md
I don't deleted them. Only was this 2 exercises. Do i have to put n3 and n4?

2023-09-26 17:44 UTC, Arsentau commented
It seems you have conficts

2023-09-26 17:53 UTC, Arsentau requested changes
The exercice 4 doesn't have its own readme file
Every file MUST have an empty new line tailing space
The name of functions must be fixed, it should be camel case, not snake case

2023-09-26 17:53 UTC, Arsentau commented on README.md
> +- [Ejercicio-3](./ej3-couting_Cards/README.md)
link to exercice 4 is missing

2023-09-30 13:10 UTC, merged